version: "3.2"
services:
  neo4j:
    image: neo4j:latest
    container_name: 'neo4j'
    environment:
      NEO4J_dbms_read__only: "false"
      #  Tuning
      # NEO4J_dbms_memory_pagecache_size: 8G
      # NEO4J_dbms_memory_heap_initial__size: 4G
      # NEO4J_dbms_memory_heap_max__size: 4G
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - './db/neo4j/data:/data'
      - './db/neo4j/conf/:/conf/'
      #/mnt/volume/neo4j-data:/data
    restart: on-failure
    networks: 
        - service-network
    command: neo4j
  backend:
    container_name: 'collector-service'
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - '8080:8080'
    volumes: 
      - './collector-service:/go/src/app'
    depends_on: 
      - 'neo4j' 
    networks: 
        - service-network

networks:
  service-network:
    driver: bridge
 
volumes:
  dgraph:
